apiVersion: v1
kind: Service
metadata:
  name: spc-svc
spec:
  type: LoadBalancer
  selector:
    app: spc
  ports:
    - name: http-8000
      port: 8000
      targetPort: 8000
      protocol: TCP
    - name: http-9000
      port: 9000
      targetPort: 9000
      protocol: TCP
